### ISSUE TITLE
Lollipop becomes unusable, slow

### ISSUE THREAD

**Issue by david4096** [BD2KGenomics/brca-website#122] opened 2016-07-21 18:05 UTC
After using the viz on safari for a few seconds it became intractably slow. Switching to the filter tab seemed to still be using resources when I changed filter options. Had to close and reopen the tab. Perhaps consider placing a button to avoid unnecessary reloading of data.

**Comment by melissacline** [comment] 2016-07-21 19:37
Mary, would you work with David (Steinberg) to reproduce / characterize this issue?

**Comment by maryjgoldman** [comment] 2016-07-22 18:35
@david4096 I'm looking around the filters and lollipop plot on Safari and I think I see at least part of what you're seeing? Source selection is normally quite fast, however if you open up the lollipop plot and then try to use the source selection filter, it is incredibly slow. I see this most pronounced on Safari but it also in Chrome and FF.

Is this what you were talking about or is there something else as well?

**Comment by david4096** [comment] 2016-07-22 21:42
Hi @maryjgoldman, the whole site became unusable in the circumstance you've reproduced. In general, the performance of zooming and panning the lollipop chart on Safari makes it unusable. A quick fix would be to show only known pathogenic and benign variants. A slightly more involved fix would be grouping elements together, and only rendering elements that are visible. The variants at high density get a different SVG element though they are all drawing to the same pixels.

**Comment by maryjgoldman** [comment] 2016-07-25 17:41
@david4096 I am not able to reproduce what you're saying. I just zoomed and panned on the lollipop chart in Safari for several minutes and didn't notice any slow down. It's maybe a bit jerky (from the beginning) but it still is quite usable.

**Comment by david4096** [comment] 2016-07-25 17:53
@maryjgoldman thanks ;). My specific pain points are that the intermediate zoom levels aren't helpful and seem to slow things down. I found the scroll wheel behavior frustrating because it would hijack when I scrolled down. I think more than a few thousand SVG elements will always cause a browser to choke.

But yes, this issue can close without messing with the chart!

**Comment by maryjgoldman** [comment] 2016-07-25 23:10
Ok, I think understand now! I think I'd like to create two issues:
1. If you have the lollipop plot up and use the source filter, the filter is incredibly slow. This is a bug that needs to be fixed.
2. I agree that the scrolling to zoom can be frustrating when you are trying to scroll down the page, especially since you can double click to zoom in anyways. I will file a feature request to remove the scroll to zoom. 

I'm going to close this and create these two new ones.

Also, can we all agree to call it a 'lolliplot'? Because that's what I keep on typing by accident.

**Closed by maryjgoldman** 2016-07-25 23:10 UTC
Labels: ready
